name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
# assignees:
#   - octocat
body:
  - type: dropdown
    id: severity
    attributes:
      label: What level of impact is this having?
      description: |
        Sev1 (High) - This is impacting multiple customers and/or facilities, with no workaround in place
        Sev2 (Medium) - This is impacting a critical impact for a single customer or facility, but there is a workaround
        Sev3 (Low) - This is irritating, but not having a major impact on operations
      options:
        - Sev1 - High
        - Sev2 - Medium
        - Sev3 - Low
    validations:
      required: true
# - type: checkboxes
#     attributes:
#       label: Is there an existing issue for this?
#       description: Please search to see if an issue already exists for the bug you encountered.
#       options:
#       - label: I have searched the existing issues
#         required: true
  - type: textarea
    id: issue-summary
    attributes:
      label: Issue Summary
      description: A concise description of what you're experiencing
      placeholder: X was expecting Y to do Z, but got _____ instead
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
      placeholder: X thought it was going to do Y
    validations:
      required: false  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened
      placeholder: When X did Y, Z happened
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false 
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any log entries, code snippets, etc that may be of use in resolving this issue
  # - type: textarea
  #   id: logs-code
  #   attributes:
  #     label: Relevant log or code output
  #     description: Please copy and paste any relevant log or code output. This will be automatically formatted into code, so no need for backticks.
  #     render: shell