name: Discussion
description: Start a discussion about something related to this application/repo
title: "[Discussion]: "
labels: ["discussion"]
body:
  - type: textarea
    id: discussion-summary
    attributes:
      label: Discussion Summary
      description: |
        Use this template to start an open discussion on a topic that does not necessarily involve an enhancement or bug. This can be an open discussion, or idea that you want to flesh out via collaboration. A discussion can lead to an enhancement or ADO backlog item.
      # placeholder: X was expecting Y to do Z, but got _____ instead
    validations:
      required: true